title: Alex Lockhart
include: ["_pages"]
baseurl: ""

future: true

embed_tweets: false

permalink: pretty
relative_permalinks: false

plugins:
  - jekyll-last-modified-at
  - jekyll-toc

toc:
  min_level: 1
  max_level: 3

sass:
  sass_dir: _sass
  style: compressed

collections:
  presentations:
    output: true

defaults:
  - scope:
      path: "**/*"
    values:
      layout: "default"
  - scope:
      path: "_posts/**/*.md"
    values:
      layout: "post"
  - scope:
      path: "_presentations/**/*.md"
    values:
      layout: "presentation"
