title: Alex Lockhart
include: ["_pages"]
exclude: ["_includes/notes_graph.json", "renovate.json"]
baseurl: ""

future: true

embed_tweets: false

permalink: pretty
relative_permalinks: false

plugins:
  - jekyll-last-modified-at

sass:
  sass_dir: _sass
  style: compressed

collections:
  notes:
    output: true
  presentations:
    output: true

defaults:
  - scope:
      path: "**/*"
    values:
      layout: "default"
  - scope:
      path: "_posts/**/*.md"
    values:
      layout: "post"
  - scope:
      path: "_notes/**/*.md"
    values:
      layout: "note"
  - scope:
      path: "_presentations/**/*.md"
    values:
      layout: "presentation"
