name: deploy

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup ruby
        uses: ruby/setup-ruby@v1.154.0
        with:
          ruby-version: "2.7.7"
          bundler-cache: true
          cache-version: 0
      - name: setup pages
        id: pages
        uses: actions/configure-pages@v3
      - name: build
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production
      - name: upload
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v2
